POST http://localhost:3333/courses
Content-Type: application/json

{
    "title": "Curso de Docker"
    
}

###

GET http://localhost:3333/courses


###

GET http://localhost:3333/courses/c97bd1f3-b7d4-4bed-8ed4-494aa3c81c1f


-------


